### ISSUE TITLE
Scope to create a version to work with Paperless-ngx ?

### ISSUE THREAD

**Issue by nodecentral** [rmitchellscott/Send2Remarkable#1]
Hi

Hope you don’t mind me asking this..

As a big Paperless-ngx user, I was wondering if you would consider (or could advise me how to do it) creating a version of your app/docker set up so it could output all created pdfs to defined mapped folder/volume, which Paperless-ngx could then monitor and pick them up from?

**Comment by rmitchellscott** [comment]
Are you wanting the app to scan email for PDFs then save them to a folder so paperless-ngx can pick them up? Would this just be one big folder?

**Comment by nodecentral** [comment]
Hi, thanks for responding..

Thinking about it some more, the app would ideally get both the attachment and the supporting email (potential merging them into a single pdf) and then place it/them into a folder for Paperless to consume - so if I’ve understood you correctly, yes they would just go into a single folder.?
